version: '2.4'

services:
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - bridge-net
    volumes:
      - ./static:/usr/share/nginx/html/static
      - ./assets:/usr/share/nginx/html/assets
      - ./index.html:/usr/share/nginx/html/index.html
      - nginx_logs:/var/log/nginx
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  web:
    build: .
    ports:
      - 8000:8000
    environment:
      - REDIS_URL=redis://redis:6379/0
      - RUNNING_IN_DOCKER=true
    env_file:
      - .env
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --loop asyncio
    volumes:
      - ./app:/workspace/code/app
    extra_hosts:
      - host.docker.internal:host-gateway
    networks:
      - bridge-net
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
      pgvector-db:
        condition: service_healthy

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nurses_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - bridge-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  pgvector-db:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: vector_db
    volumes:
      - pgvector_data:/var/lib/postgresql/data
    networks:
      - bridge-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  worker:
    build: .
    command: celery -A app.worker.celery_app worker --concurrency=1 --loglevel=info
    volumes:
      - ./app:/workspace/code/app
    environment:
      - REDIS_URL=redis://redis:6379/0
    networks:
      - bridge-net
    depends_on:
      web:
        condition: service_started
      redis:
        condition: service_healthy

  redis:
    image: redis:7
    networks:
      - bridge-net
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  dashboard:
    build: .
    command: celery --broker=redis://redis:6379/0 flower --port=5555
    ports:
      - 5557:5555
    environment:
      - REDIS_URL=redis://redis:6379/0
    networks:
      - bridge-net
    depends_on:
      worker:
        condition: service_started

volumes:
  local-vol:
    driver: local
  postgres_data:
  pgvector_data:
  nginx_logs:

networks:
  bridge-net:
    driver: bridge
