name: "Feature Request"
about: "Suggest a new feature for this project"
title: "[Feature Request]: "
labels: "enhancement"
assignees: ""
# Optional: If your organization has predefined issue types, you can reference one here.
# type: "enhancement"

body:
  - type: markdown
    attributes:
      value: |
        ## ✨ Feature Request
        
        Thank you for taking the time to suggest a new idea! 
        Please fill out as much detail as you can to help us understand your request.
  
  - type: input
    id: feature-title
    attributes:
      label: "Feature Name"
      description: "What would you like to call this feature?"
      placeholder: "e.g., Dark Mode, API Rate Limiting, etc."
    validations:
      required: true

  - type: textarea
    id: summary
    attributes:
      label: "Summary"
      description: "Brief description of the proposed feature"
      placeholder: "Provide a concise overview of what this feature would do."
    validations:
      required: true

  - type: textarea
    id: use-cases
    attributes:
      label: "Use Cases & Rationale"
      description: "Describe how and why this feature would be useful. Provide one or more examples or scenarios."
      placeholder: "Explain the situations in which you or others would use this feature."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: "Possible Alternatives"
      description: "Have you considered any other solutions or alternatives? If so, list them here."
      placeholder: "e.g., plugin usage, workaround scripts, etc."

  - type: textarea
    id: additional-context
    attributes:
      label: "Additional Context"
      description: "Anything else you’d like to share: screenshots, references, code samples, etc."
      placeholder: "Add any extra information that could help us evaluate your request."
