name: Labeler
on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  label:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
    - name: Label PR
      if: |
        !(github.event.pull_request.user.type == 'Bot' || 
        contains(github.event.pull_request.user.login, '[bot]'))
      uses: actions/labeler@v4
      with:
        repo-token: "${{ secrets.MV_TOKEN }}"
        configuration-path: .github/labeler.yml
        sync-labels: false
        dot: true